# Generated by Django 4.1.2 on 2022-10-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chall_name', models.CharField(max_length=50)),
                ('decription', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Web exploit', 'Web'), ('Cryptography', 'Crypto'), ('Pwable', 'Pwn'), ('Reverse', 'Re')], max_length=20)),
                ('img', models.CharField(blank=True, max_length=50)),
                ('flag', models.CharField(max_length=255)),
                ('point', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=32)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
