# Generated by Django 4.1.2 on 2022-10-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chall',
            name='type',
            field=models.CharField(choices=[('Web exploit', 'Web'), ('Cryptography', 'Crypto'), ('Pwnable', 'Pwn'), ('Reverse', 'Re')], max_length=20),
        ),
    ]
