# Generated by Django 4.1.2 on 2022-10-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_chall_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chall',
            name='chall_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
