# Generated by Django 4.1.2 on 2022-10-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_chall_chall_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chall',
            name='author',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
